#!/bin/bash

set -o errexit -o nounset -o pipefail

replicas=(
    1.releases.grapheneos.org
    2.releases.grapheneos.org
    3.releases.grapheneos.org
    4.releases.grapheneos.org
    5.releases.grapheneos.org
)

for replica in ${replicas[@]}; do
    echo
    echo Deploying to $replica
    echo

    rsync -rptvl --progress --delete /etc/letsencrypt/ $replica:/etc/letsencrypt
    rsync -rptvl --progress --delete /etc/nginx/ocsp-cache/ $replica:/etc/nginx/ocsp-cache
    ssh root@$replica nginx -s reload
done
