#!/bin/bash

set -o errexit -o nounset -o pipefail

servers=(
    primary.releases.grapheneos.org
    replica1.releases.grapheneos.org
)

for replica in ${servers[@]}; do
    echo
    echo Deploying to $replica
    echo

    rsync -rptv --chmod=D755,F644 --progress --delete releases/ $replica:/srv/releases
done
