#!/bin/bash

set -o errexit -o nounset -o pipefail

exec {fd}< releases
if ! flock -n $fd; then
    echo releases already locked >&2
    exit 1
fi

. servers.sh

for replica in ${servers[@]}; do
    echo
    echo Deploying to $replica
    echo

    rsync -rptv --fsync --chmod=D755,F644 --progress --delete releases/ $replica:/srv/releases
done
