#!/bin/bash

set -o errexit -o nounset -o pipefail

./validate-static
./process-static

servers=(
    0.releases.grapheneos.org
    1.releases.grapheneos.org
)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/releases.grapheneos.org)

    if [[ $active = /srv/releases.grapheneos.org_a ]]; then
        target=/srv/releases.grapheneos.org_b
    else
        target=/srv/releases.grapheneos.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote rm -rf $target
    ssh $remote cp -a $active $target
    rsync -rpcv --chmod=D755,F644 --delete static_tmp/ $remote:$target
    ssh $remote sync -f $target
    ssh $remote ln -snf $target /srv/releases.grapheneos.org
    ssh $remote sync /srv/releases.grapheneos.org

    cp nginx/nginx.conf nginx.conf.tmp
    sed -i "s|/srv/releases.grapheneos.org|$target|" nginx.conf.tmp
    rsync -rpcv --chmod=D755,F644 --delete nginx.conf.tmp $remote:/etc/nginx/nginx.conf
    ssh $remote sync -f /etc/nginx/nginx.conf
    ssh $remote nginx -s reload

    echo
    echo active is now $target
done
