#!/bin/bash

set -o errexit -o nounset -o pipefail

exec {fd}< releases
if ! flock -n $fd; then
    echo releases already locked >&2
    exit 1
fi

. servers.sh

parallel "rsync -rptv --fsync --chmod=D755,F644 --progress --delete releases/ {}:/srv/releases 2>&1 >logs/{}.log" ::: ${servers[@]}
tail -n +1 logs/*.log
