#!/bin/bash

set -o errexit -o nounset -o pipefail

./process-static

. servers.sh

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/releases.grapheneos.org)

    if [[ $active = /srv/releases.grapheneos.org_a ]]; then
        target=/srv/releases.grapheneos.org_b
    else
        target=/srv/releases.grapheneos.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote rm -rf $target
    ssh $remote cp -a $active $target
    rsync -rptcv --chmod=D755,F644 --delete static-tmp/ $remote:$target
    ssh $remote sync -f $target
    ssh $remote ln -snf $target /srv/releases.grapheneos.org
    ssh $remote sync /srv/releases.grapheneos.org

    sed "s|/srv/releases.grapheneos.org|$target|" nginx-tmp/nginx.conf > nginx-tmp/nginx.conf.root
    rsync -rptcv --chmod=D755,F644 --delete nginx-tmp/nginx.conf.root $remote:/etc/nginx/nginx.conf
    rsync -rptcv --chmod=D755,F644 --delete nginx-tmp/snippets/ $remote:/etc/nginx/snippets
    ssh $remote 'sync /etc/nginx/nginx.conf /etc/nginx/snippets/*'
    ssh $remote nginx -s reload

    echo
    echo active is now $target
    echo
done
