#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s extglob

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already processing/deploying static files >&2
    exit 1
fi

./process-static $fd

. servers.sh

remote=root@mia.releases.grapheneos.org

rsync -pcv --chmod=F644 --fsync --preallocate mirrors $remote:/etc/mirrors

# use last modified timestamps from mia.releases.grapheneos.org
rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate $remote:/srv/releases.grapheneos.org/ static-production
rsync -rpcv --chmod=D755,F644 --delete --fsync --preallocate static-tmp/ static-production
for f in static-production/**.*(br|gz); do
    touch -r "${f%.*}" "$f"
done

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/releases.grapheneos.org)

    if [[ $active = /srv/releases.grapheneos.org_a ]]; then
        target=/srv/releases.grapheneos.org_b
    else
        target=/srv/releases.grapheneos.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote "rm -rf $target && cp -a $active $target"
    rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate static-production/ $remote:$target
    ssh $remote "ln -snf $target /srv/releases.grapheneos.org && sync /srv/releases.grapheneos.org"

    echo "root $target;" > nginx-tmp/root_releases.grapheneos.org.conf
    rsync -pcv --chmod=644 --fsync --preallocate nginx-tmp/{nginx.conf,mime.types,root_releases.grapheneos.org.conf,security-headers-releases.conf} $remote:/etc/nginx/
    ssh $remote systemctl reload nginx

    echo
    echo active is now $target
    echo
done
