#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

if [[ ${GITHUB_ACTIONS:-false} != true ]]; then
    source venv/bin/activate
fi

if [[ $# -eq 1 ]]; then
    fd=$1
else
    touch lock
    exec {fd}< lock
fi

if ! flock -n $fd; then
    echo already processing/deploying static files >&2
    exit 1
fi

rm -rf nginx-tmp
cp -a nginx nginx-tmp

gixy nginx-tmp/nginx.conf

rm -rf static-tmp
cp -a static static-tmp

for file in static-tmp/**/*.json; do
    json_verify < "$file" >/dev/null
    json_reformat -m < "$file" | sponge "$file"
done

brotli_k() {
    brotli -k "$@"
}
export -f brotli_k

zopfli_preserve_time() {
    zopfli "$1"
    touch -r "$1" "$1.gz"
}
export -f zopfli_preserve_time

find static-tmp -name '*.xml' -exec xmllint --noblanks {} --output {} \;
find static-tmp -regex '.+\.\(ico\|json\|svg\|txt\|xml\)' |
    parallel -q ::: brotli_k zopfli_preserve_time :::: -
