#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

for file in static_tmp/**/*.@(json|webmanifest); do
    json_reformat -m < "$file" | sponge "$file"
done

rm -rf static_tmp
cp -a static static_tmp
find static_tmp -name '*.xml' -exec xmllint --noblanks {} --output {} \;
find static_tmp -regex '.+\.\(ico\|json\|txt\|xml\)' \
    -exec zopfli {} \; -exec touch -r {} {}.gz \; \
    -exec brotli -k {} \;
