#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

rm -rf static_tmp
cp -a static static_tmp

for file in static_tmp/**/*.@(json|webmanifest); do
    json_reformat -m < "$file" | sponge "$file"
done

brotli_k() {
    brotli -k "$@"
}
export -f brotli_k

zopfli_preserve_time() {
    zopfli "$1"
    touch -r "$1" "$1.gz"
}
export -f zopfli_preserve_time

find static_tmp -name '*.xml' -exec xmllint --noblanks {} --output {} \;
find static_tmp -regex '.+\.\(ico\|json\|txt\|xml\)' |
    parallel -q ::: brotli_k zopfli_preserve_time :::: -
