#!/bin/bash

set -o errexit -o nounset -o pipefail

primary=root@primary.releases.grapheneos.org
replicas=(
    replica1.releases.grapheneos.org
)

rsync -rptvl --delete $primary:/etc/letsencrypt replicate_tmp/
rsync -rptvl --delete $primary:/srv/mta-sts replicate_tmp/
rsync -rptvl --delete $primary:/var/www/releases replicate_tmp/

for replica in ${replicas[@]}; do
    echo
    echo Deploying to $replica
    echo

    rsync -rptvl --delete replicate_tmp/letsencrypt/ $replica:/etc/letsencrypt
    ssh $replica systemctl start certbot-ocsp-fetcher.service

    rsync -rptvl --delete replicate_tmp/mta-sts/ $replica:/srv/mta-sts
    rsync -rptvl --delete replicate_tmp/releases/ $replica:/var/www/releases
done
