#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

for file in static/**/*.@(json|webmanifest); do
    json_verify < "$file" >/dev/null
done

xmllint --noout static/**/*.xml
