load_module modules/ngx_http_brotli_static_module.so;

error_log syslog:server=unix:/run/nginx-error-log,nohostname;
# leave stderr open but minimize duplicate logging to it
error_log stderr emerg;

worker_processes auto;
worker_rlimit_nofile 65536;
worker_shutdown_timeout 1d;

events {
    worker_connections 16384;
}

http {
    root /var/empty;

    include mime.types;
    default_type application/octet-stream;

    charset utf-8;

    keepalive_requests 16;
    keepalive_timeout 0;
    server_tokens off;
    msie_padding off;

    client_max_body_size 1k;
    client_body_buffer_size 1k;
    client_header_buffer_size 1k;
    large_client_header_buffers 2 1k;

    reset_timedout_connection on;
    client_body_timeout 15s;
    client_header_timeout 15s;
    send_timeout 30s;

    max_ranges 1;

    resolver [::1];
    resolver_timeout 15s;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers on;
    ssl_conf_command Options PrioritizeChaCha;

    ssl_certificate /etc/letsencrypt/live/releases.grapheneos.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/releases.grapheneos.org/privkey.pem;

    # managed externally in noswap tmpfs
    ssl_session_ticket_key /etc/tls/session-ticket-keys/4.key;
    ssl_session_ticket_key /etc/tls/session-ticket-keys/3.key;
    ssl_session_ticket_key /etc/tls/session-ticket-keys/2.key;
    ssl_session_ticket_key /etc/tls/session-ticket-keys/1.key;
    ssl_session_ticket_key /etc/tls/session-ticket-keys/next.key;
    ssl_session_timeout 1d;
    ssl_buffer_size 4k;

    log_format main '$connection-$connection_requests $remote_addr $remote_user $ssl_session_reused $ssl_protocol $server_protocol '
        '$host $request_method "$request_uri" $status $request_length $body_bytes_sent/$bytes_sent '
        '$request_time $upstream_connect_time/$upstream_header_time/$upstream_response_time '
        '$upstream_cache_status "$http_referer" "$http_user_agent"';
    access_log syslog:server=unix:/run/nginx-access-log,nohostname main;
    log_subrequest on;
    log_not_found off;

    gzip_proxied any;
    gzip_vary on;

    if_modified_since before;

    aio threads;
    aio_write on;

    include releases.conf;

    server {
        listen 80 default_server backlog=4096 fastopen=16 rcvbuf=2048 sndbuf=2048;
        listen [::]:80 default_server backlog=4096 fastopen=16 rcvbuf=2048 sndbuf=2048;

        # https://trac.nginx.org/nginx/ticket/2012
        location / {
            return 421;
        }
    }

    server {
        listen 443 default_server ssl backlog=4096 fastopen=16;
        listen [::]:443 default_server ssl backlog=4096 fastopen=16;
        ssl_reject_handshake on;

        # https://trac.nginx.org/nginx/ticket/2012
        location / {
            return 421;
        }
    }

    server {
        listen unix:/run/nginx/status.sock;

        access_log off;

        location = / {
            stub_status;
        }

        location / {
            return 404;
        }
    }
}
